### ISSUE TITLE
Who update OpenProjet via Portainer ?

### ISSUE THREAD

**Issue by damienvidalcabm** [opf/openproject-docker-compose#55]
Good morning,

I would like to migrate from OpenProject 12.5.4 to 12.5.6.
How to do via Portainer ?

Thx

**Comment by LufinityLucas** [comment]
Are you running it as a stack? In that case, go to Stacks -> <your stack> -> Editor -> (modify the tag if required) -> Update the stack -> Re-pull image and redeploy -> Update.

If you're running it as a stand-alone conatiner, go to Containers -> <your container> -> Recreate -> Re-pull image -> Recreate.

**EDIT:** FOr stand-alone container, you can select Duplicate/Edit instead of Recreate if you need to change the tag (make sure Always pull the image is hooked), and then just click Deploy the container.

**Comment by openpkrump** [comment]
Hi damienvidalcabm , thank you for reaching out to us. Inquiries like these one are handled within our helpdesk system. If you have issues like these and have an enterprise plan, please send us an email to [support@openproject.com](mailto:support@openproject.com)
